db:
  restart: always
  image: postgres:9.5
  volumes:
    - ./db/data:/var/lib/postgresql/data
web:
  restart: always
  build: ./web/
  command: python /code/manage.py runserver 0.0.0.0:8000
  volumes:
    - ./web/code/:/code
  ports:
    - "7000:8000"
  links:
    - db
